[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gpa_calculator_TBD"
version = "0.0.1"
authors = [
  {name="Hai Dang Le"}, {name="Esther Finotti"}, {name="Miles Porter"} , {name="Yasemin Fekadu"} , { name="Sam Haddad"}
]
description = "A GPA Calculator package"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/YasF-bit/prj-1-"
"Bug Tracker" = "https://github.com/YasF-bit/prj-1-/issues"

[tool.hatch.build.targets.wheel]
packages = ["gpa_calculator_TBD"]
